### ISSUE TITLE
Sort of work under Mac (no w and no tinfo) but segment fault if do ?c8

### ISSUE THREAD

**Issue by kwccoin** [jborza/solitaire-cli#1]
Try to do make but ncursesw and tinfo both in the way in macOS.

Quite elegant job.  Great works.

**Comment by kwccoin** [comment]
I change the ncursesw to ncurses and remove the "-ltinfo" seems it is running !

**Comment by kwccoin** [comment]
Well it runs and I nearly got my first stack done, just to put the cards to the foundation ... and then segment fault!  Sigh.  Guess this bypass is not totally worked.  Still got a good game especially when you think you lost and you find a way ... should done.

**Comment by kwccoin** [comment]
Seems if you nearly finish and type the wrong move to foundation (at least the last one) it segmentation fault 11
![Screenshot 2020-07-13 at 5 50 40 PM crop](https://user-images.githubusercontent.com/7194447/87291527-08821180-c532-11ea-8677-7ef69fe115ec.png)

![Screenshot 2020-07-13 at 5 49 33 PM](https://user-images.githubusercontent.com/7194447/87291292-afb27900-c531-11ea-8eec-54e808edfb3f.png)

**Comment by kwccoin** [comment]
Got the bug ... if you type ?c8 it will segment fault.

**Comment by kwccoin** [comment]
Install under ubuntu under docker under Mac, the unicode does not inside the image (even after locale set to us utf8);  but the gdb has indicated clearly the issue is related to line 198 int is_empty.  Trying if one has an A wf5 is invalid command but wf11 ok but not wf12 (and all c8 has problem).  This points to the data structure char pile_types[] = "dwffffccccccc"; at line 325.  Too late night to me but would investigate further.

**Comment by jborza** [comment]
Fixed the segfault on c8 (or f5 or any number beyond c7 or fr4) with https://github.com/jborza/solitaire-cli/commit/d2ac8016518eb37c729396af71db50592a534090

**Comment by jborza** [comment]
It was basically caused by `get_pile` function having no sanity checks, so it attempted to get N-th pile, which was outside of the game_state pile **piles array. 

Thanks for the report!

I'll try to add a makefile target macos to compile without ncursesw when I get my hands on a macbook.
